html = open('INFORME--@RanmsesRuiz-v3.html', 'r', encoding='utf-8').read()
o = html.count('<div')
c = html.count('</div>')
print(f'Div balance: {o} open, {c} close = {o-c}')
print(f'Chars: {len(html):,}')
print(f'CAP-03: {html.count("CAP-03")}')
print(f'CAP-04: {html.count("CAP-04")}')
print(f'CAP-05: {html.count("CAP-05")}')
print(f'CAP-06: {html.count("CAP-06")}')
print(f'CAP-01: {html.count("CAP-01")}')
print(f'CAP-02: {html.count("CAP-02")}')
print(f'EV-10: {html.count("EV-10")}')
print(f'SS7: {html.count("SS7")}')
print(f'2 a 3 semanas: {html.count("2 a 3 semanas")}')
print(f'cuatro vectores: {html.count("cuatro vectores")}')
print(f'tres vectores: {html.count("tres vectores")}')
print(f'10 capturas: {"10</b>" in html}')
print(f'google-calendar: {html.count("google-calendar")}')
print(f'captura-metadata: {html.count("captura-metadata")}')
print(f'data-extradida: {html.count("data-extradida")}')
print(f'hoy.png: {html.count("hoy.png")}')
