html = open('INFORME--@RanmsesRuiz-v3.html', 'r', encoding='utf-8').read()
o = html.count('<div')
c = html.count('</div>')
print(f'Div balance: {o} open, {c} close = {o-c}')
print(f'Chars: {len(html):,}')
print(f'9 fuentes residual: {html.count("9 fuentes")}')
print(f'10 fuentes: {html.count("10 fuentes")}')
print(f'EV-10-A: {html.count("EV-10-A")}')
print(f'EV-10-B: {html.count("EV-10-B")}')
print(f'IMSI 334050: {html.count("334050141620218")}')
print(f'VECTOR 4: {html.count("VECTOR 4")}')
print(f'SS7: {html.count("SS7")}')
print(f'EV-10: {html.count("EV-10")}')
print(f'14 capturas: {html.count("14</b>")}')
